### ISSUE TITLE
View status

### ISSUE THREAD

**Issue by sudoevans** [mHassan11/auto-whatsapp#1]
Hey, How can I implement Auto view status?

**Comment by mHassan11** [comment]
Hey,
You can selenium to add that functionality. I am not actively maintaining this repo, otherwise this seems like interesting feature. If you end of implementing it, feel free to push.

**Comment by sudoevans** [comment]
Thanks, I have never used selenium, but I know I can learn it quick. 
I will give you feedback when I find a walkthrough.
Thanks, Hassan
